Add disabled grove port power switch
esphome/home-assistant-voice-pe pull request #194
Opened 2024-11-09 19:45 UTC by jesserockz

The grove port 5v pin is activated only when GPIO46 of the ESP32-S3 is turned on.

2024-11-10 13:46 UTC, balloob commented on home-assistant-voice.yaml
> +    disabled_by_default: true
I don’t want to expose this as an entity at all. People need to update yaml. Maybe we can make it a substitute value at the top of the file that people seee when they adopt it ?

2024-11-10 20:02 UTC, jesserockz commented on home-assistant-voice.yaml
> +    entity_category: config
```suggestion
```

2024-11-27 15:57 UTC, jlpouffier requested changes
@jesserockz Can you just add a small comment so that if people are reading and searching the groove port, they know what they need to do?

2024-11-27 15:57 UTC, jlpouffier commented on home-assistant-voice.yaml
> +    restore_mode: RESTORE_DEFAULT_OFF
```suggestion
    # Change this to ALWAYS_ON if you are planning to use the Grove port
    restore_mode: RESTORE_DEFAULT_OFF
```

2024-11-27 19:45 UTC, balloob approved these changes

2024-11-27 19:46 UTC, merged